version: '3.8'
services:
  smartfs-web:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.smartfs-web.rule=Host(`smartfscore.aproitsolutions.in`)"
      - "traefik.http.routers.smartfs-web.entrypoints=websecure"
      - "traefik.http.routers.smartfs-web.tls=true"
      - "traefik.http.routers.smartfs-web.tls.certresolver=letsencrypt"
      - "traefik.http.services.smartfs-web.loadbalancer.server.port=8000"
    networks:
      - web

networks:
  web:
    external: true

